### ISSUE TITLE
7.9.1 doesn't save pulley diameter settings for custom machine

### ISSUE THREAD

**Issue by b3nno** [MarginallyClever/Makelangelo-software#213] opened 2016-12-09 19:28 UTC
7.9.1 doesn't save pulley diameter settings for custom machine.
wenn I set a value for pulley diameter, it doesn't save in the machine. 
I checked it with the D2 command. I allways get 0.35 for both pulleys...

**Comment by i-make-robots** [comment] 2016-12-10 07:45
how the heck is it 0.35?  the default is 1.27323954

**Comment by i-make-robots** [comment] 2017-07-30 03:28
Duplicate of #212

**Closed by i-make-robots** 2017-07-30 03:28 UTC
